# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e6793478be2f28c9bc9d7e9f6310618f4470a06edb8bbda1e133d39739c461c013c6af3ef54a849671ba542fee7f63bbd13245eee9185c820243e3249397b25

test:
  secret_key_base: d2a09616fc692cd57cf7b9d8be5db14e19d2b06b0ad118323bf79b5c2cebf61b542b4af64fc159f5374f28d8e0f5b1cf8ebb9b8ed2d9abd85759794387060296

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
