# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a81980cb9cae9a8a956d2b7db5132d535cdf1d35a5305f1d7780fcd7257fec27218a99bd146bb6bc8e91ef5632dee6eebeee15d0e97baba041eb5e88416ff77

test:
  secret_key_base: 471343089606bec40d14b112015be71482d6d5fbb5efae18a8cf37c6f469c614c82c8d73b64e9ca11bb9527e78e25f4e96fe0ef10573da8be0174b30520b13a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
